export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/v1/auth/login',
    REGISTER: '/api/v1/auth/register',
    REFRESH: '/api/v1/auth/refresh',
    LOGOUT: '/api/v1/auth/logout',
    ME: '/api/v1/auth/me',
    FORGOT_PASSWORD: '/api/v1/auth/forgot-password',
    RESET_PASSWORD: '/api/v1/auth/reset-password',
  },
  SESSIONS: {
    BASE: '/api/v1/learning-sessions',
    BY_ID: (id: string) => `/api/v1/learning-sessions/${id}`,
    ANALYSIS: (id: string) => `/api/v1/learning-sessions/${id}/analysis`,
    BLUEPRINT: (id: string) => `/api/v1/learning-sessions/${id}/blueprint`,
    VALIDATION: (id: string) => `/api/v1/learning-sessions/${id}/validation`,
    SUBMIT_ANSWER: (id: string) => `/api/v1/learning-sessions/${id}/validation/answer`,
    REFLECTION: (id: string) => `/api/v1/learning-sessions/${id}/reflection`,
    REPORT: (id: string) => `/api/v1/learning-sessions/${id}/report`,
    GUIDED_LEARNING: (id: string) => `/api/v1/learning-sessions/${id}/guided-learning`,
    RESUME: (id: string) => `/api/v1/learning-sessions/${id}/resume`,
    COMPLETE: (id: string) => `/api/v1/learning-sessions/${id}/complete`,
  },
  DASHBOARD: {
    STUDENT: '/api/v1/dashboard',
    FACULTY: '/api/v1/faculty/dashboard',
    INSTITUTION: '/api/v1/institution/dashboard',
  },
  FACULTY: {
    COURSES: '/api/v1/faculty/courses',
    COURSE_BY_ID: (id: string) => `/api/v1/faculty/courses/${id}`,
    STUDENTS: '/api/v1/faculty/students',
    STUDENT_BY_ID: (id: string) => `/api/v1/faculty/students/${id}`,
    ANALYTICS: '/api/v1/faculty/analytics',
    INTERVENTIONS: '/api/v1/faculty/interventions',
    INSIGHTS: '/api/v1/faculty/insights',
    REPORTS: '/api/v1/faculty/reports',
  },
  RECOMMENDATIONS: {
    BASE: '/api/v1/recommendations',
    STUDENT: '/api/v1/recommendations',
    ACCEPT: (id: string) => `/api/v1/recommendations/${id}/complete`,
    REGENERATE: '/api/v1/recommendations/regenerate',
  },
  PORTFOLIO: {
    BASE: '/api/v1/portfolio',
    DNA: '/api/v1/portfolio/dna',
    TIMELINE: '/api/v1/portfolio/timeline',
    EXPORT: '/api/v1/portfolio/export',
  },
  REPORTS: {
    BASE: '/api/v1/reports',
    BY_ID: (id: string) => `/api/v1/reports/${id}`,
    EXPORT: (id: string) => `/api/v1/reports/${id}/export`,
    ALL: '/api/v1/reports',
    SHARE: '/api/v1/reports/share',
  },
  REFLECTIONS: {
    BASE: '/api/v1/reflection',
    BY_SESSION: (id: string) => `/api/v1/reflection/${id}`,
  },
  ACHIEVEMENTS: {
    BASE: '/api/v1/achievements',
    CLAIM: (id: string) => `/api/v1/achievements/${id}/claim`,
  },
  MENTOR: {
    CHAT: '/api/v1/mentor/chat',
  },
  NOTIFICATIONS: {
    BASE: '/api/v1/notifications',
    READ: (id: string) => `/api/v1/notifications/${id}/read`,
    READ_ALL: '/api/v1/notifications/read-all',
  },
} as const;
